// File generated by Gopher Sauce
// DO NOT EDIT!!
package types

import (
	"encoding/json"
	"log"

	"github.com/cheikhshift/db"
)

// Asserts first argument, a map, as struct
// PageComp. This function is used with template functionality.
func CastPageComp(args ...interface{}) *PageComp {

	s := PageComp{}
	mapp := args[0].(db.O)
	if _, ok := mapp["_id"]; ok {
		mapp["Id"] = mapp["_id"]
	}
	data, _ := json.Marshal(&mapp)

	err := json.Unmarshal(data, &s)
	if err != nil {
		log.Println(err.Error())
	}

	return &s
}

// Create a new PageComp struct and return the pointer.
func NewPageComp() *PageComp { return &PageComp{} }

// Asserts first argument, a map, as struct
// FeedGroup. This function is used with template functionality.
func CastFeedGroup(args ...interface{}) *FeedGroup {

	s := FeedGroup{}
	mapp := args[0].(db.O)
	if _, ok := mapp["_id"]; ok {
		mapp["Id"] = mapp["_id"]
	}
	data, _ := json.Marshal(&mapp)

	err := json.Unmarshal(data, &s)
	if err != nil {
		log.Println(err.Error())
	}

	return &s
}

// Create a new FeedGroup struct and return the pointer.
func NewFeedGroup() *FeedGroup { return &FeedGroup{} }
