// This file was generated by Gopher Sauce.
// UPDATE IT TO BETTER TEST YOUR CODE.
package types

import (
	"testing"
)

func TestPageComp(t *testing.T) {

	t.Error("Test for data type PageComp not implemented!!")
}

func TestFeed(t *testing.T) {

	t.Error("Test for data type Feed not implemented!!")
}

func TestFeedGroup(t *testing.T) {

	t.Error("Test for data type FeedGroup not implemented!!")
}
