// File generated by Gopher Sauce
// DO NOT EDIT!!
package methods

import "strings"

//
func IsActive(args ...interface{}) string {
	url := args[0]
	lookup := args[1]

	if strings.Contains(url.(string), lookup.(string)) {

		return "active"
	}

	return ""

}
