// This file was generated by Gopher Sauce.
// UPDATE IT TO BETTER TEST YOUR CODE.
package methods

import (
	"testing"
)

func TestIsActive(t *testing.T) {

	t.Error("Test for method IsActive not implemented!!")
}

func TestGetState(t *testing.T) {

	t.Error("Test for method GetState not implemented!!")
}
