
					// File generated by Gopher Sauce
					// DO NOT EDIT!!
					package methods

					import gosweb "github.com/cheikhshift/gos/web"
					import "2-edu/types"
					import "2-edu/api/globals"

					
						// 
						func IsActive(args ...interface{}) string {
							url string := args[0]
								 lookup string := args[1]
								
    return "active"

						}