
					// File generated by Gopher Sauce
					// DO NOT EDIT!!
					package methods

					import gosweb "github.com/cheikhshift/gos/web"
					import "2-edu/types"
					import "2-edu/api/globals"

					
						// 
						func GetState(args ...interface{}) types.PageComp {
							r *http.Request := args[0]
								
    return types.PageComp{ "/" }

						}