// File generated by Gopher Sauce
// DO NOT EDIT!!
package handlers

import gosweb "github.com/cheikhshift/gos/web"

import sessionStore "2-edu/api/sessions"

import templates "2-edu/api/templates"

import methods "2-edu/api/methods"

import types "2-edu/types"
import "2-edu/api/globals"

var WebCache = gosweb.NewCache()

func mResponse(v interface{}) string {
	data, _ := json.Marshal(&v)
	return string(data)
}

func ApiAttempt(w http.ResponseWriter, r *http.Request) (callmet bool) {
	var response string
	var session *sessions.Session

	var er error

	if session, er = sessionStore.Store.Get(r, "session-"); er != nil {
		session, _ = sessionStore.Store.New(r, "session-")
	}

	if r.Method == "RESET" {
		return true
	}
	if callmet {
		session.Save(r, w)
		session = nil
		if response != "" {
			//Unmarshal json
			//w.Header().Set("Access-Control-Allow-Origin", "*")
			w.Header().Set("Content-Type", "application/json")
			w.Write([]byte(response))
		}
		return
	}
	session = nil
	return
}
