// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"2-edu/api/assets"
	"2-edu/types"
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	"log"
	"text/template"

	"github.com/fatih/color"
)

//
// Renders HTML of template
// PageEnd with struct types.PageComp
func PageEnd(d types.PageComp) string {
	return netbPageEnd(d)
}

// recovery function used to log a
// panic.
func templateFNPageEnd(localid string, d interface{}) {
	if n := recover(); n != nil {
		color.Red(fmt.Sprintf("Error loading template in path (core/PageEnd) : %s", localid))
		// log.Println(n)
		DebugTemplatePath(localid, d)
	}
}

var templateIDPageEnd = "tmpl/core/PageEnd.tmpl"

// Render template with JSON string as
// data.
func netPageEnd(args ...interface{}) string {

	localid := templateIDPageEnd
	var d *types.PageComp
	defer templateFNPageEnd(localid, d)
	if len(args) > 0 {
		jso := args[0].(string)
		var jsonBlob = []byte(jso)
		err := json.Unmarshal(jsonBlob, d)
		if err != nil {
			return err.Error()
		}
	} else {
		d = &types.PageComp{}
	}

	output := new(bytes.Buffer)

	if _, ok := templateCache.Get(localid); !ok || !Prod {

		body, er := assets.Asset(localid)
		if er != nil {
			return ""
		}
		var localtemplate = template.New("PageEnd")
		localtemplate.Funcs(TemplateFuncStore)
		var tmpstr = string(body)
		localtemplate.Parse(tmpstr)
		body = nil
		templateCache.Put(localid, localtemplate)
	}

	erro := templateCache.JGet(localid).Execute(output, d)
	if erro != nil {
		color.Red(fmt.Sprintf("Error processing template %s", localid))
		DebugTemplatePath(localid, d)
	}
	var outps = output.String()
	var outpescaped = html.UnescapeString(outps)
	d = nil
	output.Reset()
	output = nil
	args = nil
	return outpescaped

}

// alias of template render function.
func bPageEnd(d types.PageComp) string {
	return netbPageEnd(d)
}

//

// template render function
func netbPageEnd(d types.PageComp) string {
	localid := templateIDPageEnd
	defer templateFNPageEnd(localid, d)
	output := new(bytes.Buffer)

	if _, ok := templateCache.Get(localid); !ok || !Prod {

		body, er := assets.Asset(localid)
		if er != nil {
			return ""
		}
		var localtemplate = template.New("PageEnd")
		localtemplate.Funcs(TemplateFuncStore)
		var tmpstr = string(body)
		localtemplate.Parse(tmpstr)
		body = nil
		templateCache.Put(localid, localtemplate)
	}

	erro := templateCache.JGet(localid).Execute(output, d)
	if erro != nil {
		log.Println(erro)
	}
	var outps = output.String()
	var outpescaped = html.UnescapeString(outps)
	d = types.PageComp{}
	output.Reset()
	output = nil
	return outpescaped
}

// Unmarshal a json string to the template's struct
// type
func netcPageEnd(args ...interface{}) (d types.PageComp) {
	if len(args) > 0 {
		var jsonBlob = []byte(args[0].(string))
		err := json.Unmarshal(jsonBlob, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	} else {
		d = types.PageComp{}
	}
	return
}

// Create a struct variable of template.
func cPageEnd(args ...interface{}) (d types.PageComp) {
	if len(args) > 0 {
		d = netcPageEnd(args[0])
	} else {
		d = netcPageEnd()
	}
	return
}
