// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import "2-edu/types"
import "2-edu/api/assets"
import gosweb "github.com/cheikhshift/gos/web"

// Template path
var templateIDPageStart = "tmpl/core/PageStart.tmpl"

//
// Renders HTML of template
// PageStart with struct gosweb.NoStruct
func PageStart(d gosweb.NoStruct) string {
	return netbPageStart(d)
}

// Render template with JSON string as
// data.
func netPageStart(args ...interface{}) string {

	// Get data from JSON
	var d = netcPageStart(args...)
	return netbPageStart(d)

}

// template render function
func netbPageStart(d gosweb.NoStruct) string {
	localid := templateIDPageStart
	name := "PageStart"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcPageStart(args ...interface{}) (d gosweb.NoStruct) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
