// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import "2-edu/types"
import "2-edu/api/assets"
import gosweb "github.com/cheikhshift/gos/web"

// Template path
var templateIDURLTool = "tmpl/ui/URLTool.tmpl"

//
// Renders HTML of template
// URLTool with struct gosweb.NoStruct
func URLTool(d gosweb.NoStruct) string {
	return netbURLTool(d)
}

// Render template with JSON string as
// data.
func netURLTool(args ...interface{}) string {

	// Get data from JSON
	var d = netcURLTool(args...)
	return netbURLTool(d)

}

// template render function
func netbURLTool(d gosweb.NoStruct) string {
	localid := templateIDURLTool
	name := "URLTool"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcURLTool(args ...interface{}) (d gosweb.NoStruct) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
