// This file was generated by Gopher Sauce.
// UPDATE IT TO BETTER TEST YOUR CODE.
package templates

import (
	"testing"
)

func TestPageStart(t *testing.T) {

	t.Error("Test for template PageStart not implemented!!")
}

func TestPageEnd(t *testing.T) {

	t.Error("Test for template PageEnd not implemented!!")
}

func TestNavBar(t *testing.T) {

	t.Error("Test for template NavBar not implemented!!")
}

func TestFeed(t *testing.T) {

	t.Error("Test for template Feed not implemented!!")
}

func TestURLTool(t *testing.T) {

	t.Error("Test for template URLTool not implemented!!")
}
