// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import "2-edu/types"
import "2-edu/api/assets"
import gosweb "github.com/cheikhshift/gos/web"

// Template path
var templateIDNavBar = "tmpl/ui/NavBar.tmpl"

//
// Renders HTML of template
// NavBar with struct gosweb.NoStruct
func NavBar(d gosweb.NoStruct) string {
	return netbNavBar(d)
}

// Render template with JSON string as
// data.
func netNavBar(args ...interface{}) string {

	// Get data from JSON
	var d = netcNavBar(args...)
	return netbNavBar(d)

}

// template render function
func netbNavBar(d gosweb.NoStruct) string {
	localid := templateIDNavBar
	name := "NavBar"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcNavBar(args ...interface{}) (d gosweb.NoStruct) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
