// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"2-edu/api/assets"
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	"log"
	"text/template"

	gosweb "github.com/cheikhshift/gos/web"
	"github.com/fatih/color"
)

//
// Renders HTML of template
// Feed with struct gosweb.NoStruct
func Feed(d gosweb.NoStruct) string {
	return netbFeed(d)
}

// recovery function used to log a
// panic.
func templateFNFeed(localid string, d interface{}) {
	if n := recover(); n != nil {
		color.Red(fmt.Sprintf("Error loading template in path (ui/Feed) : %s", localid))
		// log.Println(n)
		DebugTemplatePath(localid, d)
	}
}

var templateIDFeed = "tmpl/ui/Feed.tmpl"

// Render template with JSON string as
// data.
func netFeed(args ...interface{}) string {

	localid := templateIDFeed
	var d *gosweb.NoStruct
	defer templateFNFeed(localid, d)
	if len(args) > 0 {
		jso := args[0].(string)
		var jsonBlob = []byte(jso)
		err := json.Unmarshal(jsonBlob, d)
		if err != nil {
			return err.Error()
		}
	} else {
		d = &gosweb.NoStruct{}
	}

	output := new(bytes.Buffer)

	if _, ok := templateCache.Get(localid); !ok || !Prod {

		body, er := assets.Asset(localid)
		if er != nil {
			return ""
		}
		var localtemplate = template.New("Feed")
		localtemplate.Funcs(TemplateFuncStore)
		var tmpstr = string(body)
		localtemplate.Parse(tmpstr)
		body = nil
		templateCache.Put(localid, localtemplate)
	}

	erro := templateCache.JGet(localid).Execute(output, d)
	if erro != nil {
		color.Red(fmt.Sprintf("Error processing template %s", localid))
		DebugTemplatePath(localid, d)
	}
	var outps = output.String()
	var outpescaped = html.UnescapeString(outps)
	d = nil
	output.Reset()
	output = nil
	args = nil
	return outpescaped

}

// alias of template render function.
func bFeed(d gosweb.NoStruct) string {
	return netbFeed(d)
}

//

// template render function
func netbFeed(d gosweb.NoStruct) string {
	localid := templateIDFeed
	defer templateFNFeed(localid, d)
	output := new(bytes.Buffer)

	if _, ok := templateCache.Get(localid); !ok || !Prod {

		body, er := assets.Asset(localid)
		if er != nil {
			return ""
		}
		var localtemplate = template.New("Feed")
		localtemplate.Funcs(TemplateFuncStore)
		var tmpstr = string(body)
		localtemplate.Parse(tmpstr)
		body = nil
		templateCache.Put(localid, localtemplate)
	}

	erro := templateCache.JGet(localid).Execute(output, d)
	if erro != nil {
		log.Println(erro)
	}
	var outps = output.String()
	var outpescaped = html.UnescapeString(outps)
	d = gosweb.NoStruct{}
	output.Reset()
	output = nil
	return outpescaped
}

// Unmarshal a json string to the template's struct
// type
func netcFeed(args ...interface{}) (d gosweb.NoStruct) {
	if len(args) > 0 {
		var jsonBlob = []byte(args[0].(string))
		err := json.Unmarshal(jsonBlob, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	} else {
		d = gosweb.NoStruct{}
	}
	return
}

// Create a struct variable of template.
func cFeed(args ...interface{}) (d gosweb.NoStruct) {
	if len(args) > 0 {
		d = netcFeed(args[0])
	} else {
		d = netcFeed()
	}
	return
}
