// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"2-edu/api/assets"
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	"html/template"
	"log"

	gosweb "github.com/cheikhshift/gos/web"
	"github.com/fatih/color"
)

//
// Renders HTML of template
// NavBar with struct gosweb.NoStruct
func NavBar(d gosweb.NoStruct) string {
	return netbNavBar(d)
}

// recovery function used to log a
// panic.
func templateFNNavBar(localid string, d interface{}) {
	if n := recover(); n != nil {
		color.Red(fmt.Sprintf("Error loading template in path (ui/NavBar) : %s", localid))
		// log.Println(n)
		DebugTemplatePath(localid, d)
	}
}

var templateIDNavBar = "tmpl/ui/NavBar.tmpl"

// Render template with JSON string as
// data.
func netNavBar(args ...interface{}) string {

	localid := templateIDNavBar
	var d *gosweb.NoStruct
	defer templateFNNavBar(localid, d)
	if len(args) > 0 {
		jso := args[0].(string)
		var jsonBlob = []byte(jso)
		err := json.Unmarshal(jsonBlob, d)
		if err != nil {
			return err.Error()
		}
	} else {
		d = &gosweb.NoStruct{}
	}

	output := new(bytes.Buffer)

	if _, ok := templateCache.Get(localid); !ok || !Prod {

		body, er := assets.Asset(localid)
		if er != nil {
			return ""
		}
		var localtemplate = template.New("NavBar")
		localtemplate.Funcs(TemplateFuncStore)
		var tmpstr = string(body)
		localtemplate.Parse(tmpstr)
		body = nil
		templateCache.Put(localid, localtemplate)
	}

	erro := templateCache.JGet(localid).Execute(output, d)
	if erro != nil {
		color.Red(fmt.Sprintf("Error processing template %s", localid))
		DebugTemplatePath(localid, d)
	}
	var outps = output.String()
	var outpescaped = html.UnescapeString(outps)
	d = nil
	output.Reset()
	output = nil
	args = nil
	return outpescaped

}

// alias of template render function.
func bNavBar(d gosweb.NoStruct) string {
	return netbNavBar(d)
}

//

// template render function
func netbNavBar(d gosweb.NoStruct) string {
	localid := templateIDNavBar
	defer templateFNNavBar(localid, d)
	output := new(bytes.Buffer)

	if _, ok := templateCache.Get(localid); !ok || !Prod {

		body, er := assets.Asset(localid)
		if er != nil {
			return ""
		}
		var localtemplate = template.New("NavBar")
		localtemplate.Funcs(TemplateFuncStore)
		var tmpstr = string(body)
		localtemplate.Parse(tmpstr)
		body = nil
		templateCache.Put(localid, localtemplate)
	}

	erro := templateCache.JGet(localid).Execute(output, d)
	if erro != nil {
		log.Println(erro)
	}
	var outps = output.String()
	var outpescaped = html.UnescapeString(outps)
	d = gosweb.NoStruct{}
	output.Reset()
	output = nil
	return outpescaped
}

// Unmarshal a json string to the template's struct
// type
func netcNavBar(args ...interface{}) (d gosweb.NoStruct) {
	if len(args) > 0 {
		var jsonBlob = []byte(args[0].(string))
		err := json.Unmarshal(jsonBlob, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	} else {
		d = gosweb.NoStruct{}
	}
	return
}

// Create a struct variable of template.
func cNavBar(args ...interface{}) (d gosweb.NoStruct) {
	if len(args) > 0 {
		d = netcNavBar(args[0])
	} else {
		d = netcNavBar()
	}
	return
}
