// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import "2-edu/types"
import "2-edu/api/assets"
import gosweb "github.com/cheikhshift/gos/web"

// Template path
var templateIDPageEnd = "tmpl/core/PageEnd.tmpl"

//
// Renders HTML of template
// PageEnd with struct gosweb.NoStruct
func PageEnd(d gosweb.NoStruct) string {
	return netbPageEnd(d)
}

// Render template with JSON string as
// data.
func netPageEnd(args ...interface{}) string {

	// Get data from JSON
	var d = netcPageEnd(args...)
	return netbPageEnd(d)

}

// template render function
func netbPageEnd(d gosweb.NoStruct) string {
	localid := templateIDPageEnd
	name := "PageEnd"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netcPageEnd(args ...interface{}) (d gosweb.NoStruct) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
